[project]
name = "batch-deploy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.14"
dependencies = [
    "fastparquet>=2024.11.0",
    "pandas>=2.3.3",
    "prefect>=3.5.0",
    "scikit-learn>=1.1.0",
]
